Add balance function and tests
GoRunMaxim/Balanced-Parentheses pull request #1
Opened 2020-12-30 09:06 UTC by GoRunMaxim

2020-12-30 09:21 UTC, papahmsolo commented on Balance_test.go
> +			isBalanced: true,
this test should fail

2020-12-30 09:23 UTC, papahmsolo requested changes
Not only you should check the number of the various parentheses matches, but also check if the order is correct.

2020-12-31 08:07 UTC, papahmsolo requested changes
Nice job! You got the algorithm right!

2020-12-31 08:07 UTC, papahmsolo commented on Balance.go
> +			stack = append(stack, byte(v))
We won't need this conversion if we have a stack of `rune`

2020-12-31 08:07 UTC, papahmsolo commented on Balance.go
> +			}
We can get rid of this long switch, try to store the matching brackets in a map.

2020-12-31 08:07 UTC, papahmsolo commented on Balance_test.go
> +			isBalanced: false,
Let's test more corner cases, like an empty string. double closing bracket in the end

2020-12-31 10:31 UTC, GoRunMaxim commented on Balance.go
> +func Balance(brackets string) bool {
correct, didn't set my ml settings

2020-12-31 10:32 UTC, GoRunMaxim commented on Balance.go
> +			stack = append(stack, byte(v))
Fixed

2020-12-31 10:36 UTC, GoRunMaxim commented on Balance_test.go
> +			isBalanced: false,
Fixed

2020-12-31 11:18 UTC, GoRunMaxim commented on Balance.go
> +			}
Fixed

2021-01-04 08:00 UTC, papahmsolo requested changes
Looks great! 

Let's also make this work with expressions containing not only brackets, to validate things like this:
`((1 + 2) * 3) - 4)/5`

2021-01-04 08:21 UTC, GoRunMaxim commented on Balance.go
> +			i, ok := last[stack[n]]
Nope. Deleted

2021-01-04 08:22 UTC, GoRunMaxim commented on Balance.go
> +			}
✅

2021-01-04 09:52 UTC, papahmsolo requested changes
Cool, almost ready to move on

2021-01-04 09:52 UTC, papahmsolo commented on Balance.go
> +}
Isn't it a map of _matching_ brackets? I think the name is not self-descriptive here

2021-01-04 09:52 UTC, papahmsolo commented on Balance.go
> +		} else if v == '}' || v == ')' || v == ']' {
If-else is fine, but `switch` is a bit cleaner

2021-01-04 09:52 UTC, papahmsolo commented on Balance.go
> +			i := last[stack[n]]
`i` stands for index? Not sure about this name

2021-01-04 09:52 UTC, papahmsolo commented on Balance.go
> +			}
These `ifs` have the same return value, maybe we can combine them?

2021-01-04 11:21 UTC, GoRunMaxim commented on Balance.go
> +			i := last[stack[n]]
✅

2021-01-04 11:23 UTC, GoRunMaxim commented on Balance.go
> +}
✅

2021-01-04 13:33 UTC, papahmsolo commented on Balance.go
> +		} else if v == '}' || v == ')' || v == ']' {
Try it out and we can compare then

2021-01-04 13:34 UTC, papahmsolo commented on Balance.go
> +			}
Just combine two conditions into one if, simple as that

2021-01-04 14:53 UTC, papahmsolo commented on Balance.go
> +			stack = stack[:n]
I think the compiler can make that optimization with `n` for you. We write code for humans in the first place.
```			
if len(stack) == 0 || matchBrackets[stack[len(stack)-1]] != v {
    return false
}
stack = stack[:len(stack)-1]```

2021-01-04 14:55 UTC, papahmsolo requested changes
Shouldn't file names be in lowercase?

2021-01-04 14:56 UTC, papahmsolo commented on Balance.go
> +			stack = stack[:n]
This is optional, though

2021-01-04 15:53 UTC, papahmsolo approved these changes

2021-01-04 15:53 UTC, merged