Add a service that generates a random sequence of parentheses of the length n.
GoRunMaxim/Balanced-Parentheses pull request #2
Opened 2021-01-05 13:56 UTC by GoRunMaxim

2021-01-05 15:59 UTC, papahmsolo requested changes
Not bad!

I think we can also create a separate package for the service.

2021-01-05 15:59 UTC, papahmsolo commented on start.go
> +	"github.com/gorilla/mux"
We'll get to this router later in the project, it's overkill right now. Use the standard library for routing.

2021-01-05 15:59 UTC, papahmsolo commented on parentheses.go
> +func Generate(w http.ResponseWriter, r *http.Request) {
Let's not mix up the parentheses generator with http handle, create a separate func.

2021-01-05 20:54 UTC, GoRunMaxim commented on parentheses.go
> +func Generate(w http.ResponseWriter, r *http.Request) {
✅

2021-01-06 05:28 UTC, papahmsolo requested changes
Looks good, let's also move funcs to the right packages

2021-01-06 05:28 UTC, papahmsolo commented on parentheses.go
> +		randNum, err := rand.Int(rand.Reader, big.NewInt(6))
Cool, so you know about `crypto/rand`, that's great! However, we just want to generate a random sequence of brackets, not a password :)

2021-01-06 05:28 UTC, papahmsolo commented on parentheses.go
> +		s += strconv.QuoteRune(brackets[randNum.Int64()])
Concatenating strings this way would be very inefficient for large numbers. I'd append brackets to a slice and then convert it to a string.

2021-01-06 05:28 UTC, papahmsolo commented on parentheses.go
> +	brackets := []rune{'{', '[', '(', '}', ']', ')'}
This slice does not change, we can move it out of the func

2021-01-06 05:28 UTC, papahmsolo commented on parentheses.go
> +	}
Should we return a 500 here? Looks more of a client problem

2021-01-06 05:28 UTC, papahmsolo commented on parentheses.go
> +	w.Header().Set("Content-Type", "application/json")
Not sure, why would we need a JSON here, we can simply return plain text

2021-01-08 07:55 UTC, papahmsolo requested changes
Nice work, Max!

- Let's combine service and start into one file.
- We need a main package to run the service, let's add one :)

2021-01-08 07:55 UTC, papahmsolo commented on parentheses/parentheses.go
> +	brackets = []rune{'{', '[', '(', '}', ']', ')'}
Let's fix the length of the `brackets` slice and make it an array with `[...]rune`

2021-01-08 07:55 UTC, papahmsolo commented on parentheses/parentheses.go
> +	for g := 0; g < length; g++ {
Not an issue, but why `g` and not `i`, for instance?

2021-01-08 07:55 UTC, papahmsolo commented on parentheses/parentheses.go
> +		// gosec linter wont show us error (crypto package instead of math)
Probably shouldn't be in the source code, configure your linter locally

2021-01-08 07:55 UTC, papahmsolo commented on parentheses/parentheses.go
> +		randNum := rand.Int31n(6)
Generate is not random, it's returning the same sequence all the time, you need to seed your random generator

2021-01-08 07:55 UTC, papahmsolo commented on parentheses/parentheses_test.go
> +	}
We can return more details, say the position of invalid rune

2021-01-08 08:43 UTC, GoRunMaxim commented on parentheses/parentheses.go
> +		// gosec linter wont show us error (crypto package instead of math)
I'will fix this, but doesn't usually team use same linters? I think its good practice

2021-01-08 12:22 UTC, GoRunMaxim commented on parentheses/parentheses.go
> +		randNum := rand.Int31n(6)
Is it the solution: add "rand.Seed(time.Now().UTC().UnixNano())" before for loop? Or It could be better way to seed the generator?

2021-01-08 12:50 UTC, GoRunMaxim commented
`var bracketsAmount int
	for _, v := range resp {
		switch v {
		case '{', '(', '[', '}', ')', ']':
			bracketsAmount++
		}
	}`

2021-01-08 12:52 UTC, GoRunMaxim commented
`var bracketsAmount int
	for _, v := range resp {
		switch v {
		case '{', '(', '[', '}', ')', ']':
			bracketsAmount++
		}
	}`
We expect that resp contains brackets only. So could we just change it all to len(resp) instead of counting them in range loop?

2021-01-08 13:11 UTC, GoRunMaxim commented
**We need a main package to run the service, let's add one :)**

U mead simply add empty directory or what?

2021-01-11 11:44 UTC, papahmsolo requested changes
Looks great!

2021-01-11 11:44 UTC, papahmsolo commented on parentheses/parentheses.go
> +	var bracketsSlice []rune
We can allocate the slice using `make` and the `length` provided in the argument.

2021-01-11 11:44 UTC, papahmsolo commented on parentheses/parentheses.go
> +		randNum := rand.Int31n(6)
- Do we need an `int32` specifically? Let's use `rand.Intn`
- Let's get rid of the magic number `6` and use `length ` instead

2021-01-11 11:44 UTC, papahmsolo commented on parentheses/parentheses_test.go
> +		bodyString := Generate(test.length)
- It's not necessarily a `bodyString`, is it?

2021-01-11 11:44 UTC, papahmsolo commented on parentheses/parentheses_test.go
> +}
Let's also check the string contains only parentheses

2021-01-11 11:44 UTC, papahmsolo commented on service/service.go
> +	i, err := strconv.Atoi(length)
What if `length` is negative?

2021-01-11 11:44 UTC, papahmsolo commented on service/service.go
> +		http.Error(w, err.Error(), http.StatusBadRequest)
Cool, let's return some concrete error message. `strconv.Atoi: parsing` is not clear + you're exposing details of your implementation.

2021-01-11 13:19 UTC, GoRunMaxim commented on parentheses/parentheses_test.go
> +		bodyString := Generate(test.length)
You right, actually do we need this value? I think we can delete it

2021-01-11 13:46 UTC, GoRunMaxim commented on service/service.go
> +		http.Error(w, err.Error(), http.StatusBadRequest)
Do we need to create constants that will contain error test or we can avoid it?

2021-01-12 09:31 UTC, papahmsolo requested changes
A couple of thought for improvement

2021-01-12 09:31 UTC, papahmsolo commented on parentheses/parentheses.go
> +	bracketsSlice := make([]rune, length)
We know it's a slice, don't we? No need to put in the name.

2021-01-12 09:31 UTC, papahmsolo commented on service/service.go
> +		log.Print("Length cannot be negative:", err)
`err` is always `nil` at this point

2021-01-12 09:31 UTC, papahmsolo commented on service/service.go
> +	if length < 0 {
We can combine the cases as they're both a client error

2021-01-12 09:31 UTC, papahmsolo commented on service/service.go
> +	address = ":8080" // address of server
I think it's okay to put it in `ListenAndServe`

2021-01-12 09:31 UTC, papahmsolo commented on parentheses/parentheses_test.go
> +	}
What about `len(resp) != amount`?

2021-01-12 09:31 UTC, papahmsolo commented on parentheses/parentheses_test.go
> +			t.Errorf("not bracket: %v, %s", v, strconv.QuoteRune(v))
Fail this test and you'll get Unicode points, but you're probably expecting strings

2021-01-13 07:15 UTC, papahmsolo requested changes
Good job Max!

Test helpers are good when you want to reuse them across multiple test functions, but for `Generate()` we use them only once, so we might just want to move the helpers to the test function.

2021-01-13 07:15 UTC, papahmsolo commented on parentheses/parentheses_test.go
> +func TestGenService(t *testing.T) {
Are we testing the service?

2021-01-13 15:28 UTC, papahmsolo requested changes
Cool, almost ready to merge :)

2021-01-13 15:28 UTC, papahmsolo commented on parentheses/parentheses_test.go
> +				t.Errorf("%s not bracket at position: %d, generated string is %s", strconv.QuoteRune(v), i, genBrackets)
No need to convert the rune. How about doing it this way:
`t.Errorf("non-bracket symbol %q at position: %d, generated string is %q", v, i, genBrackets)`
Remember, we can quote using `%q`

2021-01-14 06:11 UTC, papahmsolo approved these changes
Well done! Moving on!

2021-01-14 06:11 UTC, merged