Add Report func
GoRunMaxim/Balanced-Parentheses pull request #3
Opened 2021-01-14 07:12 UTC by GoRunMaxim

Add the report func which calls the service N = 1000 times for each of the strings of the length 2,4,6,8,10. It calculates the percent of balanced strings for each length and print the results to stdout.

2021-01-14 13:55 UTC, papahmsolo requested changes
Cool!

Let's also not kill the program if one http request fails, it does not influence the result of the report dramatically. But let's keep the logging as you do!

2021-01-14 13:55 UTC, papahmsolo commented on report/report.go
> +		for i := 0; i < 1000; i++ {
Let's make `1000` a constant

2021-01-14 13:55 UTC, papahmsolo commented on report/report.go
> +			}()
This might sound a little surprising, but that is one of the cases where you might ignore the error, there's nothing you can really do if it occurs.

2021-01-14 13:55 UTC, papahmsolo commented on report/report.go
> +			if status := resp.StatusCode; status != http.StatusOK {
Why do we have a `status` variable?)

2021-01-14 14:06 UTC, GoRunMaxim commented on report/report.go
> +			}()
Golinter told me that its bad practise to ignore error, so at least we need to log it =)

2021-01-14 14:19 UTC, GoRunMaxim commented on report/report.go
> +			}()
Yes, but the linter told me that its bad idea not to check error

2021-01-15 10:26 UTC, papahmsolo commented on report/report.go
> +			}()
In general, you should never ignore errors, but rather handle them. As I mentioned, this is one of these rare cases when you can ignore it. Here's why, you close the body to free resources, but if you get an error, you cannot handle it anyhow, but if you report the error, you still can't do anything about it. And it does not make sense to terminate the program. Do you can safely ignore it.

2021-01-15 10:32 UTC, papahmsolo requested changes
Cool!

We're calling the service sequentially, but we don't have to! Let's add some concurrency to the program 👍

2021-01-18 09:15 UTC, papahmsolo requested changes
Cool!

We're parallelizing only one part of the program, let's make http call concurrently too

2021-01-18 09:15 UTC, papahmsolo commented on report/report.go
> +	}
Let's see if we need this slice of structs at all?

2021-01-18 09:15 UTC, papahmsolo commented on report/report.go
> +				resp.StatusCode, http.StatusOK)
We know we expect `200`, so no need to mention it in the log message. But the message is good 👍

2021-01-18 09:15 UTC, papahmsolo commented on report/report.go
> +			fmt.Printf("Percent of balanced strings (length = %d) = %.1f\n", length, float64(percent)*100/1000)
Let's adjust the formula to use `serverCalls`

2021-01-18 09:15 UTC, papahmsolo commented on report/report.go
> +)
`const`?

2021-01-18 09:49 UTC, GoRunMaxim commented on report/report.go
> +	}
Change this to for loop 👍🏿

2021-01-18 10:03 UTC, GoRunMaxim commented on report/report.go
> +			fmt.Printf("Percent of balanced strings (length = %d) = %.1f\n", length, float64(percent)*100/1000)
✅

2021-01-20 09:47 UTC, papahmsolo requested changes
The idea with the workers is good! 
Let's handle http calls and channel send separately, it will make error handling much easier for you.

2021-01-20 09:47 UTC, papahmsolo commented on report/report.go
> +	result := make(chan bool, serverCalls)
The buffer is too big, make it smaller

2021-01-20 09:47 UTC, papahmsolo commented on report/report.go
> +		result <- false
No need for this `if`

2021-01-20 10:13 UTC, GoRunMaxim commented on report/report.go
> +		result <- false
☑️

2021-01-20 11:57 UTC, GoRunMaxim commented on report/report.go
> +	result := make(chan bool, serverCalls)
What do u think is correct size for the buffer?

2021-01-20 13:52 UTC, papahmsolo requested changes
Cool!

Let's move `report`'s code into main, probably does not deserve a separate function

2021-01-20 13:52 UTC, papahmsolo commented on report/report.go
> +const channelBuffer = 50
We can factorize these consts

2021-01-20 13:52 UTC, papahmsolo commented on report/report.go
> +	result := make(chan bool, channelBuffer)
Buffers are not necessarily should be of the same size

2021-01-20 13:52 UTC, papahmsolo commented on report/report.go
> +	}()
I'm not sure if there's a benefit of calling this code in another goroutine

2021-01-20 14:36 UTC, GoRunMaxim commented
**Let's move report's code into main, probably does not deserve a separate function**

2021-01-20 14:40 UTC, GoRunMaxim commented on report/report.go
> +	}()
So our jobs channel should either have the same size buffer as serverCalls value or we gotta call it in another goroutine. Otherwise, it will be endless waiting.

2021-01-21 10:00 UTC, papahmsolo requested changes
We have two `main` functions in the same package, let's move `report.go` back
What I meant is to move the code of the `report` function into `main` function.

2021-01-21 10:00 UTC, papahmsolo commented on main/report.go
> +	}
Let's return the error message that comes from the server.

2021-01-21 10:00 UTC, papahmsolo commented on main/report.go
> +	}
Let's stick to `err != nil` pattern, also we need to send `false` in case of error

2021-01-22 07:55 UTC, papahmsolo approved these changes
Very good!

2021-01-22 07:55 UTC, merged